/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesUxUiConversionsRouteImport } from './routes/case-studies.ux-ui-conversions'
import { Route as CaseStudiesImpressionsToClicksRouteImport } from './routes/case-studies.impressions-to-clicks'
import { Route as CaseStudiesCybersecurityZeroTrustRouteImport } from './routes/case-studies.cybersecurity-zero-trust'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesUxUiConversionsRoute =
  CaseStudiesUxUiConversionsRouteImport.update({
    id: '/ux-ui-conversions',
    path: '/ux-ui-conversions',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesImpressionsToClicksRoute =
  CaseStudiesImpressionsToClicksRouteImport.update({
    id: '/impressions-to-clicks',
    path: '/impressions-to-clicks',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesCybersecurityZeroTrustRoute =
  CaseStudiesCybersecurityZeroTrustRouteImport.update({
    id: '/cybersecurity-zero-trust',
    path: '/cybersecurity-zero-trust',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/cybersecurity-zero-trust': typeof CaseStudiesCybersecurityZeroTrustRoute
  '/case-studies/impressions-to-clicks': typeof CaseStudiesImpressionsToClicksRoute
  '/case-studies/ux-ui-conversions': typeof CaseStudiesUxUiConversionsRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/cybersecurity-zero-trust': typeof CaseStudiesCybersecurityZeroTrustRoute
  '/case-studies/impressions-to-clicks': typeof CaseStudiesImpressionsToClicksRoute
  '/case-studies/ux-ui-conversions': typeof CaseStudiesUxUiConversionsRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/cybersecurity-zero-trust': typeof CaseStudiesCybersecurityZeroTrustRoute
  '/case-studies/impressions-to-clicks': typeof CaseStudiesImpressionsToClicksRoute
  '/case-studies/ux-ui-conversions': typeof CaseStudiesUxUiConversionsRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/case-studies/$slug'
    | '/case-studies/cybersecurity-zero-trust'
    | '/case-studies/impressions-to-clicks'
    | '/case-studies/ux-ui-conversions'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/case-studies/$slug'
    | '/case-studies/cybersecurity-zero-trust'
    | '/case-studies/impressions-to-clicks'
    | '/case-studies/ux-ui-conversions'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/case-studies/$slug'
    | '/case-studies/cybersecurity-zero-trust'
    | '/case-studies/impressions-to-clicks'
    | '/case-studies/ux-ui-conversions'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/ux-ui-conversions': {
      id: '/case-studies/ux-ui-conversions'
      path: '/ux-ui-conversions'
      fullPath: '/case-studies/ux-ui-conversions'
      preLoaderRoute: typeof CaseStudiesUxUiConversionsRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/impressions-to-clicks': {
      id: '/case-studies/impressions-to-clicks'
      path: '/impressions-to-clicks'
      fullPath: '/case-studies/impressions-to-clicks'
      preLoaderRoute: typeof CaseStudiesImpressionsToClicksRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/cybersecurity-zero-trust': {
      id: '/case-studies/cybersecurity-zero-trust'
      path: '/cybersecurity-zero-trust'
      fullPath: '/case-studies/cybersecurity-zero-trust'
      preLoaderRoute: typeof CaseStudiesCybersecurityZeroTrustRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesCybersecurityZeroTrustRoute: typeof CaseStudiesCybersecurityZeroTrustRoute
  CaseStudiesImpressionsToClicksRoute: typeof CaseStudiesImpressionsToClicksRoute
  CaseStudiesUxUiConversionsRoute: typeof CaseStudiesUxUiConversionsRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesCybersecurityZeroTrustRoute:
    CaseStudiesCybersecurityZeroTrustRoute,
  CaseStudiesImpressionsToClicksRoute: CaseStudiesImpressionsToClicksRoute,
  CaseStudiesUxUiConversionsRoute: CaseStudiesUxUiConversionsRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
